<a href="https://colab.research.google.com/github/puneetbisarwal25/Deep-Learning-Basic/blob/main/First_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.10.0+cpu


In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

In [3]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


In [4]:
import torch

x = torch.tensor(5)

print(x)
print(x.shape)

tensor(5)
torch.Size([])


## Creating a Tensor


In [19]:
# using empty
a = torch.empty(2,3)
print(a)

tensor([[2.6988e-12, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [20]:
# check type
type(a)

torch.Tensor

In [21]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [22]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [32]:
# using rand
torch.rand(2,3)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [31]:
# without use of seed
torch.rand(2,3)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [29]:
# use of manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [33]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [35]:
# other ways

# arange
print("using a range ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using a range -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes


In [36]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [37]:
x.shape

torch.Size([2, 3])

In [38]:
torch.empty_like(x)

tensor([[          745153874, 4603929615117844480, 4590235693325746176],
        [4606266874043301888, 4605943259531837440, 4594579872357023744]])

In [39]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [40]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [44]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.4440, 0.9478],
        [0.7445, 0.4892],
        [0.2426, 0.7003]])

## Tensor Data Types

In [45]:
# find data type
x.dtype

torch.int64

In [46]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [47]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)