<a href="https://colab.research.google.com/github/puneetbisarwal25/Deep-Learning-Basic/blob/main/python_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
x = 10
name = "AI"

print(x)
print(name)

10
AI


In [4]:
numbers = [1, 2, 3, 4]

print(numbers[0])
print(numbers[-1])

1
4


In [5]:
numbers = [1, 2, 3, 4]

print(numbers[-1])

4


In [7]:
for i in range(5):
    print(i)

0
1
2
3
4


In [8]:
def add(a, b):
    return a + b

result = add(2, 3)

print(result)

5


In [9]:
class Student:

    def __init__(self, name):
        self.name = name

    def show(self):
        print(self.name)

s = Student("Rahul")

s.show()

Rahul


In [10]:
import numpy as np

a = np.array([1, 2, 3])

print(a)

[1 2 3]


In [11]:
matrix = np.array([
    [1, 2],
    [3, 4]
])

print(matrix)

[[1 2]
 [3 4]]


In [12]:
print(matrix.shape)

(2, 2)


In [13]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

C = A + B

print(C)

[[ 6  8]
 [10 12]]


In [14]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

C = np.dot(A, B)

print(C)

[[19 22]
 [43 50]]


In [15]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

print(A * B)

[ 4 10 18]


In [16]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [21]:
x = np.array([1,2,3,4,5,6])

y = x.reshape(2,3)

print(y)

[[1 2 3]
 [4 5 6]]


In [19]:
x = np.array([1,2,3,4,5,6])

y = x.reshape(3,2)

print(y)

[[1 2]
 [3 4]
 [5 6]]


Basic Math for Deep Learning


Vectors


In [22]:
[1, 2, 3]

[1, 2, 3]

Matrices

In [23]:
[[1,2],
 [3,4]]

[[1, 2], [3, 4]]

Dot Product

In [24]:
import numpy as np

W = np.array([[1, 2]])
x = np.array([[3],
              [4]])

b = 1

y = np.dot(W, x) + b

print(y)

[[12]]


Simple NumPy Neural Network Example

In [25]:
import numpy as np

# Input
x = np.array([1, 2])

# Weights
W = np.array([0.5, 0.8])

# Bias
b = 0.1

# Forward pass
y = np.dot(x, W) + b

print(y)

2.2


In [31]:
print("X Shape = ", x.shape)

X Shape (2,)


In [32]:
print("W Shape = ", W.shape)

W Shape =  (2,)


In [33]:
print(x)
print(W)
print(y)

[1 2]
[0.5 0.8]
2.2
